import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_config.dart';
import 'services/feature_flag_service.dart';
import 'services/feature_gate.dart';
import 'feature_flags_initializer.dart';
import 'main_navigation.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // await Firebase.initializeApp();

  if (kIsWeb) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.web, // from firebase_options.dart
    );
  } else {
    await Firebase.initializeApp(); // native platforms
  }

  // Initialize Feature Flag Service
  final flagService = FeatureFlagService();
  await flagService.loadFlags(); // Load once at startup
  final groups = flagService.getAvailableUserGroups(); // Load once at startup
  print("Available User Groups: $groups");

  final gate = FeatureGate(flagService);

  // Initialize sample data (uncomment to set up initial structure)
  // await FeatureFlagsInitializer.initializeSampleData(flagService);

  runApp(MyApp(flagService: flagService, gate: gate));
}

class MyApp extends StatelessWidget {
  final FeatureFlagService flagService;
  final FeatureGate gate;

  const MyApp({super.key, required this.flagService, required this.gate});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Firebase Realtime Database',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MainNavigation(flagService: flagService, gate: gate),
      debugShowCheckedModeBanner: false,
    );
  }
}
